name: run linter on each commit

on:
  push:
    branches:
      - main
    paths:
      - '**/**.go'
  pull_request:
    paths:
      - '**/**.go'
      - 'Makefile'
      - '.github/workflows/lint.yml'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install dependencies
      run: |
        sudo apt-get update

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test
